// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260218075819_AddCategoryToTodo")]
    partial class AddCategoryToTodo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("210eec23-535a-403a-b400-316651db0402"),
                            Color = "#007AFF",
                            Description = "Work related tasks",
                            Name = "Work"
                        },
                        new
                        {
                            Id = new Guid("51d48e62-31d8-43f0-ab1e-6667ec9ecf73"),
                            Color = "#FF9500",
                            Description = "Personal tasks",
                            Name = "Personal"
                        });
                });

            modelBuilder.Entity("Api.Models.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aceafa4b-6fcc-4f42-acc1-629731e9bd19"),
                            CategoryId = new Guid("210eec23-535a-403a-b400-316651db0402"),
                            Completed = true,
                            CreatedAt = new DateTime(2026, 2, 18, 7, 58, 18, 814, DateTimeKind.Utc).AddTicks(3060),
                            Title = "Learn .NET 8"
                        },
                        new
                        {
                            Id = new Guid("54676881-12fe-467f-87cc-0494e3ade227"),
                            CategoryId = new Guid("210eec23-535a-403a-b400-316651db0402"),
                            Completed = false,
                            CreatedAt = new DateTime(2026, 2, 18, 7, 58, 18, 814, DateTimeKind.Utc).AddTicks(3070),
                            Title = "Learn EF Core"
                        },
                        new
                        {
                            Id = new Guid("69b31b6b-669f-45c4-a733-45081743f913"),
                            CategoryId = new Guid("51d48e62-31d8-43f0-ab1e-6667ec9ecf73"),
                            Completed = false,
                            CreatedAt = new DateTime(2026, 2, 18, 7, 58, 18, 814, DateTimeKind.Utc).AddTicks(3070),
                            Title = "Build a Web API"
                        });
                });

            modelBuilder.Entity("Api.Models.TodoItem", b =>
                {
                    b.HasOne("Api.Models.Category", "Category")
                        .WithMany("TodoItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Api.Models.Category", b =>
                {
                    b.Navigation("TodoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
