// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260212160448_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c4fa81cc-ceef-402f-978b-c50e35e09b82"),
                            Completed = true,
                            CreatedAt = new DateTime(2026, 2, 12, 16, 4, 48, 202, DateTimeKind.Utc).AddTicks(1000),
                            Title = "Learn .NET 8"
                        },
                        new
                        {
                            Id = new Guid("61ac4ecd-adf2-425b-a48f-a2c02a8b5abe"),
                            Completed = false,
                            CreatedAt = new DateTime(2026, 2, 12, 16, 4, 48, 202, DateTimeKind.Utc).AddTicks(1010),
                            Title = "Learn EF Core"
                        },
                        new
                        {
                            Id = new Guid("b0a1b050-7de8-42b0-9fcd-ae0375c0d996"),
                            Completed = false,
                            CreatedAt = new DateTime(2026, 2, 12, 16, 4, 48, 202, DateTimeKind.Utc).AddTicks(1010),
                            Title = "Build a Web API"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
