using Microsoft.EntityFrameworkCore;
using TaskB.API.Data;
using TaskB.API.Models;

namespace TaskB.API.Services;

public class TaskService(TaskDbContext context) : ITaskService
{
    public async Task<IEnumerable<TaskDto>> GetAllAsync(string? sort, string? order)
    {
        var query = context.TodoItems.AsQueryable();

        // Simple sorting logic based on common requirements
        // The frontend requests: _sort=createdAt&_order=desc
        if (!string.IsNullOrEmpty(sort))
        {
            query = sort.ToLower() switch
            {
                "createdat" => (order?.ToLower() == "desc") 
                    ? query.OrderByDescending(t => t.CreatedAt) 
                    : query.OrderBy(t => t.CreatedAt),
                "updatedat" => (order?.ToLower() == "desc")
                    ? query.OrderByDescending(t => t.UpdatedAt)
                    : query.OrderBy(t => t.UpdatedAt),
                "title" => (order?.ToLower() == "desc")
                    ? query.OrderByDescending(t => t.Title)
                    : query.OrderBy(t => t.Title),
                _ => query // Default if unknown sort column
            };
        }
        else
        {
            // Default sort if none provided
            query = query.OrderByDescending(t => t.CreatedAt);
        }

        var items = await query.ToListAsync();

        return items.Select(MapToDto);
    }

    public async Task<TaskDto?> GetByIdAsync(string id)
    {
        var item = await context.TodoItems.FindAsync(id);
        return item == null ? null : MapToDto(item);
    }

    public async Task<TaskDto> CreateAsync(CreateTaskDto createDto)
    {
        var newItem = new TodoItem
        {
            // Id is auto-generated by the class initializer (Guid)
            Title = createDto.Title,
            Description = createDto.Description,
            Completed = false,
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow
        };

        context.TodoItems.Add(newItem);
        await context.SaveChangesAsync();

        return MapToDto(newItem);
    }

    public async Task<TaskDto?> UpdateAsync(string id, UpdateTaskDto updateDto)
    {
        var item = await context.TodoItems.FindAsync(id);
        if (item == null) return null;

        if (updateDto.Title != null) item.Title = updateDto.Title;
        if (updateDto.Description != null) item.Description = updateDto.Description;
        if (updateDto.Completed.HasValue) item.Completed = updateDto.Completed.Value;
        
        item.UpdatedAt = DateTime.UtcNow;

        await context.SaveChangesAsync();

        return MapToDto(item);
    }

    public async Task<bool> DeleteAsync(string id)
    {
        var item = await context.TodoItems.FindAsync(id);
        if (item == null) return false;

        context.TodoItems.Remove(item);
        await context.SaveChangesAsync();
        return true;
    }

    private static TaskDto MapToDto(TodoItem item)
    {
        return new TaskDto
        {
            Id = item.Id,
            Title = item.Title,
            Description = item.Description,
            Completed = item.Completed,
            CreatedAt = item.CreatedAt,
            UpdatedAt = item.UpdatedAt
        };
    }
}
